name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tox-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install tox-uv
      run: |
        uv tool install tox --with tox-uv

    - name: Run lint
      run: tox -e lint

    - name: Run pre-commit
      run: tox -e pre-commit

    - name: Run tests
      run: tox -p -m tests

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # Not required for public repos
        files: coverage.xml
        flags: unittests
        name: codecov-${{ matrix.python }}
        fail_ci_if_error: true
