name: Pytest Jira gatting
on:
   pull_request:
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        pip install tox
    - name: Run linters
      run: tox -e pep8
    - name: Run unit tests
      run: tox -e py
